# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1f8327a2-ece6-4e87-895c-b75253ecc584";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4c709e5b-9a94-4899-b1f9-abbcc4c8264c";
      fsType = "ext4";
    };

  fileSystems."/srv/storage" =
    { device = "/dev/disk/by-uuid/344d2a7a-d219-45f9-b382-1ef934c2c1be";
      fsType = "xfs";
    };

  swapDevices = [ ];
}
