{
 "title": "fail2ban",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Top offenders by max bantime",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "topk (8,\n   max by (banned_ip_addr) (\n    max_over_time (\n      {syslog_identifier=~\"fail2ban.observer\",systemd_unit=\"fail2ban.service\"}\n      | pattern \"<_> IP <banned_ip_addr> is bad: <_> - incr <_> to <f2b_bt_h>:<f2b_bt_m>:<f2b_bt_s>\"\n      | label_format f2b_bt=\"{{ add (mul .f2b_bt_h 3600) (mul .f2b_bt_m 60) .f2b_bt_s }}\"\n      | unwrap f2b_bt [$__range]\n    )\n  )\n)",
     "legendFormat": "{{ banned_ip_addr }}"
    }
   ]
  },
  {
   "title": "Top bans per host",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,sum by (host) (count_over_time({syslog_identifier=\"fail2ban.actions\"} | pattern \"<_> [<f2b_jail>] <f2b_action> <banned_ip_addr>\" | f2b_action=\"Ban\" [$__range])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Top bans per jail",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,sum by (f2b_jail) (count_over_time({syslog_identifier=\"fail2ban.actions\"} | pattern \"<_> [<f2b_jail>] <f2b_action> <banned_ip_addr>\" | f2b_action=\"Ban\" [$__range])))",
     "legendFormat": "{{f2b_jail}}"
    }
   ]
  },
  {
   "title": "Hourly ban rate per jail",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "topk(10,sum by (f2b_jail) (count_over_time({syslog_identifier=\"fail2ban.actions\"} | pattern \"<_> [<f2b_jail>] <f2b_action> <banned_ip_addr>\" | f2b_action=\"Ban\" [1h])))",
     "legendFormat": "{{f2b_jail}}"
    }
   ]
  },
  {
   "title": "Top Banned IP Addresses in range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(8,sum by (banned_ip_addr) (count_over_time({syslog_identifier=\"fail2ban.actions\"} | pattern \"<_> [<f2b_jail>] <f2b_action> <banned_ip_addr>\" | f2b_action=\"Ban\" [$__range])))",
     "legendFormat": "{{banned_ip_addr}}"
    }
   ]
  },
  {
   "title": "Top Found IP Addresses in range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(8,\n  sum by (banned_ip_addr) (\n    count_over_time (\n      {syslog_identifier=\"fail2ban.filter\",systemd_unit=\"fail2ban.service\"}\n      | pattern \"<_> [<f2b_jail>] <f2b_action> <banned_ip_addr> - <_>\"\n      | f2b_action = \"Found\"\n      [$__range]\n    )\n  )\n)",
     "legendFormat": "{{banned_ip_addr}}"
    }
   ]
  },
  {
   "title": "Hourly ban rate per host",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10,sum by (host) (count_over_time({syslog_identifier=\"fail2ban.actions\"} | pattern \"<_> [<f2b_jail>] <f2b_action> <banned_ip_addr>\" | f2b_action=\"Ban\" [1h])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hourly ban rate per jail per host",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk(10,sum by (f2b_jail, host) (count_over_time({syslog_identifier=\"fail2ban.actions\"} | pattern \"<_> [<f2b_jail>] <f2b_action> <banned_ip_addr>\" | f2b_action=\"Ban\" [1h])))",
     "legendFormat": "{{f2b_jail}} @ {{host}}"
    }
   ]
  }
 ]
}