{
 "title": "Hyprspace",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=\"hyprspace\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dial", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dial Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) ((last_over_time(libp2p_swarm_dials_per_peer_total{job=\"hyprspace\", outcome=\"success\"}[$__range] offset $__range)) + (increase(libp2p_swarm_dials_per_peer_total{job=\"hyprspace\", outcome=\"success\"}[$__range])))) / (sum by(instance) ((last_over_time(libp2p_swarm_dials_per_peer_total{job=\"hyprspace\"}[$__range] offset $__range)) + (increase(libp2p_swarm_dials_per_peer_total{job=\"hyprspace\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dial Error Reasons - $host",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance, error) ((last_over_time(libp2p_swarm_dial_errors_total{job=\"hyprspace\",instance=\"$host\"}[$__range] offset $__range)) + (increase(libp2p_swarm_dial_errors_total{job=\"hyprspace\",instance=\"$host\"}[$__range])))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "Relay Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Relayed Bytes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(libp2p_relaysvc_data_transferred_bytes_total{job=\"hyprspace\"}[$__range] offset $__range) + increase(libp2p_relaysvc_data_transferred_bytes_total{job=\"hyprspace\"}[$__range])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hole punch outcomes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(outcome) ((last_over_time(libp2p_holepunch_address_outcomes_total{job=\"hyprspace\"}[$__range] offset $__range)) + (increase(libp2p_holepunch_address_outcomes_total{job=\"hyprspace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(dir) (libp2p_rcmgr_connections{job=\"hyprspace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streams by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by(protocol) (libp2p_rcmgr_streams{job=\"hyprspace\", scope=\"protocol\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}