{
 "title": "PostgreSQL HA",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(pg_up[$__range])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Current Master",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (pg_replication_slots_active)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent as master",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (sum_over_time(pg_replication_slots_active[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff",
     "legendFormat": "{{ instance }} -> {{ application_name }}"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(instance) (pg_stat_activity_count) > 20",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Database Size",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(datname) (sum by(datname, instance) (pg_database_size_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL Size",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 5, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pg_wal_size_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total DB Size",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(sum by(instance) (pg_database_size_bytes))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}