{
 "title": "Service Health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Consul Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by(node, status) (consul_health_node_status==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consul Services",
   "type": "stat",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by(service_name, node, status) (consul_health_service_status==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blackbox Services",
   "type": "stat",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "sum by(module, target) (min_over_time (probe_success{job=~\"integrations/blackbox/default/.*\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consul Raft Peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consul_raft_peers", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 14, "x": 10, "y": 18 } }
 ]
}