{
 "title": "IPFS",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(ipfs_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IPFS Node Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"ipfs\",instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipfs_p2p_peers_total{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "New QUIC Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(quic_connections_new_total{handshake_successful=\"true\"}[10m])*600",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Gateway: Time to first block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ipfs_http_gw_first_content_block_get_latency_seconds_sum[$__rate_interval])*100",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "New TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tcp_connections_new_total[10m])*600",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"ipfs\"}[1h])",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"ipfs\",instance=\"$node\"}",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{systemd_unit=\"nginx.service\", syslog_identifier=\"nginx_access\"} | logfmt | __error__ != `LogfmtParserErr` | host_extracted =~ `.*\\.ipfs\\.privatevoid\\.net` | line_format `{{ .host }}{{ \"\\t\" }}{{ .host_extracted }}{{ \"\\t\" }} {{ .status }} {{ .request }}`"
    }
   ]
  },
  {
   "title": "Pinning Service Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{systemd_unit=\"nginx.service\", syslog_identifier=\"nginx_access\"} | logfmt | __error__ != `LogfmtParserErr` | host_extracted = `pin.privatevoid.net` | line_format `{{ .host }}{{ \"\\t\" }} {{ .status }} {{ .request }}`"
    }
   ]
  }
 ]
}